# Generated by Django 5.2.8 on 2026-06-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='authority_image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Authority (Image)'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Program Name (Image)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='authority',
            field=models.CharField(blank=True, max_length=300, verbose_name='Organising Authority'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program Name'),
        ),
    ]
