# Generated by Django 5.2.8 on 2026-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_program_authority_image_program_name_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='categories',
            field=models.CharField(blank=True, max_length=500, verbose_name='Categories (comma separated)'),
        ),
        migrations.AddField(
            model_name='program',
            name='teams',
            field=models.CharField(blank=True, max_length=500, verbose_name='Teams (comma separated)'),
        ),
    ]
